name: kanban_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.3
  go_router: ^16.2.5
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  firebase_auth: ^6.1.1
  hive_flutter: ^1.1.0
  get_it: ^8.2.0
  dio: ^5.9.0
  firebase_core: ^4.2.0
  google_fonts: ^6.3.2
  hive: ^2.2.3
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  mocktail: ^1.0.4
  fake_cloud_firestore: ^4.0.0
  hive_test: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  

flutter:
  uses-material-design: true
